CREATE TABLE IF NOT EXISTS messages (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    sender VARCHAR(16) NOT NULL,
    content VARCHAR(64) NOT NULL,
    sender_time TIMESTAMP NOT NULL,
    address SMALLINT UNSIGNED NOT NULL
);
