CREATE TABLE IF NOT EXISTS devices (
    name VARCHAR(16) NOT NULL PRIMARY KEY,
    address SMALLINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    sender VARCHAR(16) NOT NULL,
    content VARCHAR(32) NOT NULL,
    sender_time TIMESTAMP NOT NULL,
    FOREIGN KEY (sender) REFERENCES devices(name)
);
